import { Incident, Team, User, Alert, RiskPrediction, AnalyticsSummary, FieldAssignment } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_1',
    email: 'admin@civicguard.gov',
    name: 'Director Eleanor Vance',
    role: 'admin',
    department: 'Executive Administration',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr_2',
    email: 'control@civicguard.gov',
    name: 'Marcus Chen',
    role: 'control_room',
    department: 'Central Dispatch Command',
    created_at: '2026-02-01T10:30:00Z',
  },
  {
    id: 'usr_3',
    email: 'roads.officer@civicguard.gov',
    name: 'Sgt. Priya Sharma',
    role: 'department_officer',
    department: 'Roads & Infrastructure',
    created_at: '2026-02-10T14:15:00Z',
  },
  {
    id: 'usr_4',
    email: 'water.officer@civicguard.gov',
    name: 'Tariq Al-Mansoor',
    role: 'department_officer',
    department: 'Water & Sanitation',
    created_at: '2026-02-12T11:00:00Z',
  },
  {
    id: 'usr_5',
    email: 'field1@civicguard.gov',
    name: 'Carlos Mendez (Unit Alpha-1)',
    role: 'field_team',
    department: 'Roads & Infrastructure',
    created_at: '2026-03-01T08:00:00Z',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-2026-8812',
    title: 'Severe Deep Pothole with Exposed Rebar',
    description: 'Vehicle tire blown out on fast lane. Pothole roughly 40cm wide and 15cm deep near bus transit stop.',
    category: 'POTHOLE',
    severity: 'CRITICAL',
    status: 'VERIFIED',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Near Ring Road Overpass, Connaught Central, Ward 12',
      ward: 'Ward 12',
    },
    department: 'Roads & Infrastructure',
    ai_confidence: 96.4,
    report_count: 14,
    image_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T08:30:00Z',
    updated_at: '2026-08-22T10:15:00Z',
    assigned_team_id: 'team_1',
    assigned_team_name: 'Rapid Asphalt Unit 04',
    timeline: [
      { time: '08:30', status: 'REPORTED', note: 'First citizen report submitted via mobile app with GPS and photo.', actor: 'Citizen App #8192' },
      { time: '08:32', status: 'REPORTED', note: 'AI Hazard Vision model verified category POTHOLE with 96.4% confidence.', actor: 'VisionAI v4.2' },
      { time: '09:05', status: 'VERIFIED', note: 'Triage officer confirmed structural hazard level CRITICAL.', actor: 'Marcus Chen (Control Room)' },
      { time: '09:40', status: 'IN_PROGRESS', note: 'Dispatched Rapid Asphalt Unit 04 to site for hot-mix patch repair.', actor: 'Marcus Chen (Control Room)' },
    ],
  },
  {
    id: 'INC-2026-8815',
    title: 'Major Water Main Breach & Street Inundation',
    description: 'High pressure municipal water pipe rupture flooded lower underpass with 30cm standing water.',
    category: 'WATER_LEAK',
    severity: 'CRITICAL',
    status: 'IN_PROGRESS',
    location: {
      lat: 28.6289,
      lng: 77.2185,
      address: 'Barakhamba Subway Underpass, Ward 04',
      ward: 'Ward 04',
    },
    department: 'Water & Sanitation',
    ai_confidence: 98.2,
    report_count: 29,
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T07:15:00Z',
    updated_at: '2026-08-22T09:30:00Z',
    assigned_team_id: 'team_2',
    assigned_team_name: 'Hydro Emergency Squad 02',
    timeline: [
      { time: '07:15', status: 'REPORTED', note: 'Subway water leak reported by multiple commuters.', actor: 'Citizen App' },
      { time: '07:20', status: 'VERIFIED', note: 'Escalated to critical due to vehicle traffic obstruction.', actor: 'Tariq Al-Mansoor (Officer)' },
      { time: '07:45', status: 'IN_PROGRESS', note: 'Isolation valves shut off. Dewatering pump team active.', actor: 'Hydro Emergency Squad 02' },
    ],
  },
  {
    id: 'INC-2026-8819',
    title: 'Fallen Tree Branch Obstructing Power Lines',
    description: 'Large banyan bough cracked during night squall, leaning over 11kV distribution line.',
    category: 'FALLEN_TREE',
    severity: 'HIGH',
    status: 'REPORTED',
    location: {
      lat: 28.5980,
      lng: 77.2250,
      address: 'Lodhi Colony Sector 3, Avenue B, Ward 08',
      ward: 'Ward 08',
    },
    department: 'Disaster Management',
    ai_confidence: 93.8,
    report_count: 6,
    image_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T09:45:00Z',
    updated_at: '2026-08-22T09:45:00Z',
    timeline: [
      { time: '09:45', status: 'REPORTED', note: 'Citizen photo verified with AI confidence 93.8%.', actor: 'Citizen App #4410' },
    ],
  },
  {
    id: 'INC-2026-8822',
    title: 'Uncovered Stormwater Manhole in Pedestrian Walkway',
    description: 'Cast iron cover missing near school entrance. High foot-fall hazard.',
    category: 'OPEN_MANHOLE',
    severity: 'CRITICAL',
    status: 'VERIFIED',
    location: {
      lat: 28.6350,
      lng: 77.2010,
      address: 'Panchkuian Marg, Opposite Metro Pillar 42, Ward 15',
      ward: 'Ward 15',
    },
    department: 'Roads & Infrastructure',
    ai_confidence: 97.1,
    report_count: 18,
    image_url: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T06:50:00Z',
    updated_at: '2026-08-22T08:10:00Z',
    timeline: [
      { time: '06:50', status: 'REPORTED', note: 'Citizen safety report lodged.', actor: 'Citizen App #1209' },
      { time: '07:10', status: 'VERIFIED', note: 'Flagged critical for pedestrian risk.', actor: 'Marcus Chen (Control Room)' },
    ],
  },
  {
    id: 'INC-2026-8827',
    title: 'Broken High-Mast Streetlight Cluster',
    description: 'Dark junction creating blind spot for nocturnal cross-traffic.',
    category: 'BROKEN_STREETLIGHT',
    severity: 'MEDIUM',
    status: 'REPORTED',
    location: {
      lat: 28.5820,
      lng: 77.2340,
      address: 'Defence Colony Flyover Descent, Ward 22',
      ward: 'Ward 22',
    },
    department: 'Electrical',
    ai_confidence: 91.5,
    report_count: 5,
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T10:05:00Z',
    updated_at: '2026-08-22T10:05:00Z',
  },
  {
    id: 'INC-2026-8830',
    title: 'Illegal Solid Waste & Debris Accumulation',
    description: 'Construction rubble and plastic accumulation blocking natural drainage channel.',
    category: 'GARBAGE_DUMP',
    severity: 'HIGH',
    status: 'RESOLVED',
    location: {
      lat: 28.6450,
      lng: 77.2410,
      address: 'Daryaganj Service Lane, Ward 02',
      ward: 'Ward 02',
    },
    department: 'Water & Sanitation',
    ai_confidence: 95.0,
    report_count: 8,
    image_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-21T14:20:00Z',
    updated_at: '2026-08-22T06:00:00Z',
    assigned_team_id: 'team_3',
    assigned_team_name: 'Sanitation Taskforce 09',
    timeline: [
      { time: '14:20', status: 'REPORTED', note: 'Civic alert submitted.', actor: 'Citizen App #9931' },
      { time: '15:10', status: 'VERIFIED', note: 'Validated sanitation violation.', actor: 'Tariq Al-Mansoor (Officer)' },
      { time: '17:00', status: 'IN_PROGRESS', note: 'Excavator and dumper truck on site.', actor: 'Sanitation Taskforce 09' },
      { time: '06:00', status: 'RESOLVED', note: 'Site cleared and treated. Drainage unobstructed.', actor: 'Sanitation Taskforce 09' },
    ],
  },
  {
    id: 'INC-2026-8834',
    title: 'Malfunctioning Traffic Signal (Flashing Amber)',
    description: 'Signals out of synchronization at 4-way intersection causing bottleneck.',
    category: 'TRAFFIC_SIGNAL_OUT',
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    location: {
      lat: 28.6210,
      lng: 77.2120,
      address: 'Janpath & Tolstoy Marg Junction, Ward 11',
      ward: 'Ward 11',
    },
    department: 'Electrical',
    ai_confidence: 94.2,
    report_count: 22,
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    reported_at: '2026-08-22T08:12:00Z',
    updated_at: '2026-08-22T09:10:00Z',
    assigned_team_id: 'team_4',
    assigned_team_name: 'Signal Systems Squad',
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team_1',
    name: 'Rapid Asphalt Unit 04',
    department: 'Roads & Infrastructure',
    lead_name: 'Foreman Rajesh Verma',
    contact_phone: '+91 98110 44210',
    status: 'DISPATCHED',
    active_ticket_id: 'INC-2026-8812',
    active_ticket_title: 'Severe Deep Pothole with Exposed Rebar',
    members_count: 5,
    last_location: {
      lat: 28.6142,
      lng: 77.2088,
      address: 'Connaught Central Ring Road, Ward 12',
      updated_at: '5 mins ago',
    },
  },
  {
    id: 'team_2',
    name: 'Hydro Emergency Squad 02',
    department: 'Water & Sanitation',
    lead_name: 'Eng. Sarah Jenkins',
    contact_phone: '+91 98110 55102',
    status: 'DISPATCHED',
    active_ticket_id: 'INC-2026-8815',
    active_ticket_title: 'Major Water Main Breach',
    members_count: 6,
    last_location: {
      lat: 28.6291,
      lng: 77.2181,
      address: 'Barakhamba Subway, Ward 04',
      updated_at: '2 mins ago',
    },
  },
  {
    id: 'team_3',
    name: 'Sanitation Taskforce 09',
    department: 'Water & Sanitation',
    lead_name: 'Vikram Seth',
    contact_phone: '+91 98110 33890',
    status: 'AVAILABLE',
    members_count: 8,
    last_location: {
      lat: 28.6450,
      lng: 77.2410,
      address: 'Central Depot Base 3, Ward 02',
      updated_at: '12 mins ago',
    },
  },
  {
    id: 'team_4',
    name: 'Signal Systems Squad',
    department: 'Electrical',
    lead_name: 'Deepak Nair',
    contact_phone: '+91 98110 77621',
    status: 'DISPATCHED',
    active_ticket_id: 'INC-2026-8834',
    active_ticket_title: 'Malfunctioning Traffic Signal',
    members_count: 3,
    last_location: {
      lat: 28.6212,
      lng: 77.2119,
      address: 'Janpath Junction, Ward 11',
      updated_at: '4 mins ago',
    },
  },
  {
    id: 'team_5',
    name: 'Heavy Rescue & Arbor Team',
    department: 'Disaster Management',
    lead_name: 'Capt. Anita Roy',
    contact_phone: '+91 98110 88299',
    status: 'AVAILABLE',
    members_count: 7,
    last_location: {
      lat: 28.5950,
      lng: 77.2280,
      address: 'South Regional Staging Yard',
      updated_at: 'Just now',
    },
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-101',
    title: 'Monsoon Flooding Advisory — Low-Lying Underpasses',
    message: 'Barakhamba & Minto subways experiencing water logging. Commuters advised to divert via Tolstoy Marg.',
    severity: 'CRITICAL',
    area: 'Central Zone (Ward 04, Ward 12)',
    ward: 'Ward 04',
    created_by: 'Marcus Chen (Control Room)',
    created_at: '2026-08-22T07:30:00Z',
    expires_at: '2026-08-22T19:30:00Z',
    active: true,
  },
  {
    id: 'ALT-102',
    title: 'Power Line Maintenance & Tree Clearing',
    message: 'Single lane cordoned off on Lodhi Colony Sector 3 for fallen bough extraction.',
    severity: 'MEDIUM',
    area: 'Ward 08',
    ward: 'Ward 08',
    created_by: 'Sgt. Priya Sharma',
    created_at: '2026-08-22T10:00:00Z',
    expires_at: '2026-08-22T14:00:00Z',
    active: true,
  },
];

export const INITIAL_PREDICTIONS: RiskPrediction[] = [
  {
    id: 'PRED-401',
    ward: 'Ward 04',
    area_name: 'Barakhamba Lowlands',
    risk_type: 'Drainage Overflow & Surcharging',
    risk_score: 92,
    risk_level: 'CRITICAL',
    forecast_time: '+2 Hours (14:00 IST)',
    weather_factor: 'Precipitation rate 42mm/h exceeding sewer threshold',
    recommended_action: 'Pre-position high-capacity submersible dewatering pumps.',
  },
  {
    id: 'PRED-402',
    ward: 'Ward 12',
    area_name: 'Connaught Outer Arterial',
    risk_type: 'Asphalt Pothole Subsidences',
    risk_score: 86,
    risk_level: 'HIGH',
    forecast_time: '+6 Hours (18:00 IST)',
    weather_factor: 'Heavy axle load traffic + water seepage weakening sub-base',
    recommended_action: 'Deploy visual patrol and emergency cold patch unit.',
  },
  {
    id: 'PRED-403',
    ward: 'Ward 08',
    area_name: 'Lodhi Heritage Canopy Corridor',
    risk_type: 'Arboreal Limb Failure',
    risk_score: 74,
    risk_level: 'MEDIUM',
    forecast_time: 'Next 24 Hours',
    weather_factor: 'Wind gusts exceeding 55 km/h projected',
    recommended_action: 'Prune vulnerable overhanging branches on electrical corridors.',
  },
  {
    id: 'PRED-404',
    ward: 'Ward 15',
    area_name: 'Panchkuian Commercial District',
    risk_type: 'Manhole Displacement Risk',
    risk_score: 68,
    risk_level: 'MEDIUM',
    forecast_time: '+12 Hours',
    weather_factor: 'Backpressure in stormwater interceptors',
    recommended_action: 'Inspect and lock bolted stormwater grates.',
  },
];

export const INITIAL_ANALYTICS: AnalyticsSummary = {
  active_incidents: 24,
  critical_count: 5,
  teams_available: 3,
  resolved_today: 18,
  total_incidents: 142,
  avg_response_minutes: 26.4,
  resolution_rate_percent: 94.2,
  department_breakdown: [
    { department: 'Roads & Infrastructure', active: 11, resolved: 8 },
    { department: 'Water & Sanitation', active: 7, resolved: 6 },
    { department: 'Electrical', active: 4, resolved: 3 },
    { department: 'Disaster Management', active: 2, resolved: 1 },
  ],
  severity_distribution: [
    { severity: 'CRITICAL', count: 5 },
    { severity: 'HIGH', count: 9 },
    { severity: 'MEDIUM', count: 7 },
    { severity: 'LOW', count: 3 },
  ],
  weekly_trend: [
    { day: 'Mon', reported: 18, resolved: 16 },
    { day: 'Tue', reported: 24, resolved: 22 },
    { day: 'Wed', reported: 19, resolved: 18 },
    { day: 'Thu', reported: 31, resolved: 28 },
    { day: 'Fri', reported: 27, resolved: 25 },
    { day: 'Sat', reported: 14, resolved: 15 },
    { day: 'Sun', reported: 9, resolved: 11 },
  ],
};

export const INITIAL_FIELD_ASSIGNMENTS: FieldAssignment[] = [
  {
    ticket_id: 'TKT-9912',
    incident_id: 'INC-2026-8812',
    title: 'Severe Deep Pothole with Exposed Rebar',
    category: 'POTHOLE',
    priority: 'CRITICAL',
    status: 'ON_SITE',
    assigned_at: '2026-08-22T09:40:00Z',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Near Ring Road Overpass, Connaught Central, Ward 12',
      ward: 'Ward 12',
    },
    image_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    description: 'Vehicle tire blown out on fast lane. Pothole roughly 40cm wide and 15cm deep near bus transit stop. Cordon set up; hot-mix asphalt applicator warming.',
    notes: 'Traffic police assisted with lane closure at 09:55. Estimated completion 35 mins.',
  },
  {
    ticket_id: 'TKT-9914',
    incident_id: 'INC-2026-8822',
    title: 'Uncovered Stormwater Manhole in Pedestrian Walkway',
    category: 'OPEN_MANHOLE',
    priority: 'CRITICAL',
    status: 'ACKNOWLEDGED',
    assigned_at: '2026-08-22T10:10:00Z',
    location: {
      lat: 28.6350,
      lng: 77.2010,
      address: 'Panchkuian Marg, Opposite Metro Pillar 42, Ward 15',
      ward: 'Ward 15',
    },
    image_url: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=800&q=80',
    description: 'Pedestrian safety alert. Install heavy duty replacement ductile iron cover immediately.',
  },
];
